import type { Prisma, Upload } from '@prisma/client';
import { env, storageConfigured } from '@/lib/env';
import { ServiceError } from '@/lib/errors';
import { logger } from '@/lib/logger';
import { prisma } from '@/lib/prisma';
import { photo } from '@/messages/sections/photo';
import { createStorage, userPrefix } from '@/services/storage/s3';

/**
 * Upload rows and their objects (tech spec § 11). The route handler does the
 * decoding and the `putObject`; this service owns the `Upload` table, the
 * storage gauge and every object deletion, always object first, then row.
 * Every function takes `ownerId` first and scopes the root query by it.
 */

export const STAGED_UPLOAD_TTL_MS = 24 * 60 * 60 * 1000;
const CLEANUP_BATCH = 50;

// Pending `t()` migration: the photo section is not wired into en.ts yet.
const msg = (key: keyof typeof photo) => photo[key];

function notFound(): ServiceError {
  return new ServiceError(msg('photo.errors.notFound'), 'NOT_FOUND');
}

/** Deletes the object when storage is configured; otherwise logs and lets the row go. */
async function removeObject(key: string): Promise<void> {
  if (!storageConfigured) {
    logger.warn({ key }, 'storage not configured; upload row deleted without its object');
    return;
  }
  await createStorage('photos').deleteObject(key);
}

export interface StageUploadInput {
  /** Generated by the caller so the object key can carry it before the row exists. */
  id: string;
  bytes: number;
  width: number;
  height: number;
  sha256: string;
  storageKey: string;
}

export interface StagedUpload {
  id: string;
  width: number;
  height: number;
  expiresAt: Date;
}

export type UploadView = Pick<
  Upload,
  'id' | 'storageKey' | 'bytes' | 'width' | 'height' | 'status' | 'mealId'
>;

/** Sum of every live upload (`status != REMOVED`), the storage gauge of tech spec § 11. */
export async function storageUsageBytes(): Promise<number> {
  const result = await prisma.upload.aggregate({
    _sum: { bytes: true },
    where: { status: { not: 'REMOVED' } },
  });
  return result._sum.bytes ?? 0;
}

/**
 * Records a freshly stored object as `STAGED` for 24 h. Refuses with
 * `STORAGE_FULL` when the gauge plus these bytes would pass the soft limit.
 */
export async function stageUpload(
  ownerId: string,
  input: StageUploadInput,
  now: Date,
): Promise<StagedUpload> {
  const used = await storageUsageBytes();
  if (used + input.bytes > env.STORAGE_SOFT_LIMIT_BYTES) {
    throw new ServiceError(msg('photo.errors.storageFull'), 'STORAGE_FULL');
  }
  const expiresAt = new Date(now.getTime() + STAGED_UPLOAD_TTL_MS);
  const row = await prisma.upload.create({
    data: {
      id: input.id,
      userId: ownerId,
      storageKey: input.storageKey,
      bytes: input.bytes,
      width: input.width,
      height: input.height,
      sha256: input.sha256,
      status: 'STAGED',
      expiresAt,
    },
    select: { id: true, width: true, height: true },
  });
  return { ...row, expiresAt };
}

/**
 * Attaches staged uploads to a saved meal in the caller's transaction, in the
 * given order. A missing, foreign or already attached id fails the whole save.
 */
export async function attachUploads(
  tx: Prisma.TransactionClient,
  ownerId: string,
  mealId: string,
  uploadIds: string[],
): Promise<void> {
  for (const [position, id] of uploadIds.entries()) {
    const result = await tx.upload.updateMany({
      where: { id, userId: ownerId, status: 'STAGED' },
      data: { status: 'ATTACHED', mealId, position, expiresAt: null },
    });
    if (result.count !== 1) throw notFound();
  }
}

/** Removes a photo from a saved meal: object deleted, row kept as `REMOVED`, food record untouched. */
export async function removeUpload(ownerId: string, uploadId: string): Promise<void> {
  const row = await prisma.upload.findFirst({
    where: { id: uploadId, userId: ownerId, status: { not: 'REMOVED' } },
    select: { id: true, storageKey: true },
  });
  if (!row) throw notFound();
  await removeObject(row.storageKey);
  await prisma.upload.update({
    where: { id: row.id },
    data: { status: 'REMOVED', mealId: null, position: null, expiresAt: null },
  });
}

/** Deletes a staged (not yet attached) upload: object first, then row. */
export async function deleteStagedUpload(ownerId: string, uploadId: string): Promise<void> {
  const row = await prisma.upload.findFirst({
    where: { id: uploadId, userId: ownerId, status: 'STAGED' },
    select: { id: true, storageKey: true },
  });
  if (!row) throw notFound();
  await removeObject(row.storageKey);
  await prisma.upload.delete({ where: { id: row.id } });
}

/**
 * The staged objects of a draft, in the order asked, for meal analysis. Every
 * id must be the owner's and still staged, otherwise `NOT_FOUND`.
 */
export async function readStagedImages(ownerId: string, uploadIds: string[]): Promise<Buffer[]> {
  if (uploadIds.length === 0) return [];
  const rows = await prisma.upload.findMany({
    where: { id: { in: uploadIds }, userId: ownerId, status: 'STAGED' },
    select: { id: true, storageKey: true },
  });
  const byId = new Map(rows.map((row) => [row.id, row.storageKey]));
  if (uploadIds.some((id) => !byId.has(id))) throw notFound();
  const storage = createStorage('photos');
  return Promise.all(uploadIds.map((id) => storage.getObject(byId.get(id) as string)));
}

/** A staged or attached upload of this owner, or null (the photo route answers 404 on null). */
export async function getUploadForView(
  ownerId: string,
  uploadId: string,
): Promise<UploadView | null> {
  return prisma.upload.findFirst({
    where: { id: uploadId, userId: ownerId, status: { not: 'REMOVED' } },
    select: {
      id: true,
      storageKey: true,
      bytes: true,
      width: true,
      height: true,
      status: true,
      mealId: true,
    },
  });
}

async function deleteRows(rows: Array<{ id: string; storageKey: string }>): Promise<number> {
  let deleted = 0;
  for (const row of rows) {
    try {
      await removeObject(row.storageKey);
      await prisma.upload.delete({ where: { id: row.id } });
      deleted += 1;
    } catch (error) {
      logger.warn({ err: error, uploadId: row.id }, 'upload cleanup skipped this row');
    }
  }
  return deleted;
}

/**
 * One batch of expired staged uploads, object first, then row. Returns how
 * many rows were deleted; the cleanup task loops while a batch is full.
 */
export async function expireStagedUploads(now: Date, batch = CLEANUP_BATCH): Promise<number> {
  const rows = await prisma.upload.findMany({
    where: { status: 'STAGED', expiresAt: { lt: now } },
    select: { id: true, storageKey: true },
    orderBy: { expiresAt: 'asc' },
    take: batch,
  });
  return deleteRows(rows);
}

/** Uploads of expired drafts (TS-§21.18). Only still-staged rows are touched. */
export async function deleteUploadsForDrafts(uploadIds: string[]): Promise<number> {
  if (uploadIds.length === 0) return 0;
  const rows = await prisma.upload.findMany({
    where: { id: { in: uploadIds }, status: 'STAGED' },
    select: { id: true, storageKey: true },
  });
  return deleteRows(rows);
}

/** Every object under the user's prefix, for the account purge. Rows go with the `User` cascade. */
export async function deleteUserObjects(userId: string): Promise<number> {
  if (!storageConfigured) return 0;
  const storage = createStorage('photos');
  const keys = await storage.listKeys(userPrefix(userId));
  for (const key of keys) await storage.deleteObject(key);
  return keys.length;
}
